### ISSUE TITLE
Direct Links

### ISSUE THREAD

**Issue by voidstern** [mattbirchler/Fiery-Feeds-Themes#1]
Just a suggestion, but it would be easier to install themes on the phone with direct links in the form of 
`fiery://addTheme/[theme url]`

i.e. for Halloween: `fiery://addTheme/https%3A%2F%2Fbirchtree.nyc3.digitaloceanspaces.com%2FFiery%2520Halloween.fftheme`

**Comment by mattbirchler** [comment]
That’s a great idea, thanks! I just updated the readme to account for that.
